version: "3.9"

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - airflow

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    # this is for persisting the connection data so
    # we don't have to reconnect to pgdatabase every time we re run docker compose
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8081:80

volumes:
  pgadmin-data:


networks:
  airflow:
    # this network represents the airflow network in another docker-compose file
    external:
      name: airflow_default
